//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edi.Advance.BTEC.UiTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Edi.Advance.BTEC.UiTests.UI", typeof(UI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will need to attach your assignment brief to the Assignment Checking Service application form.\r\nYou can download your brief below..
        /// </summary>
        internal static string ACSPopupContent {
            get {
                return ResourceManager.GetString("ACSPopupContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://qualifications.pearson.com/en/support/Services/assignment-checking-service.html.
        /// </summary>
        internal static string ACSUrl {
            get {
                return ResourceManager.GetString("ACSUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACSView.
        /// </summary>
        internal static string ACSViewPage {
            get {
                return ResourceManager.GetString("ACSViewPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Course.
        /// </summary>
        internal static string AddToCourse {
            get {
                return ResourceManager.GetString("AddToCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Wish List.
        /// </summary>
        internal static string AddToWishList {
            get {
                return ResourceManager.GetString("AddToWishList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applied Science.
        /// </summary>
        internal static string AppliedScience {
            get {
                return ResourceManager.GetString("AppliedScience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        internal static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive.
        /// </summary>
        internal static string Archive {
            get {
                return ResourceManager.GetString("Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archived.
        /// </summary>
        internal static string Archived {
            get {
                return ResourceManager.GetString("Archived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessor.
        /// </summary>
        internal static string Assessor {
            get {
                return ResourceManager.GetString("Assessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment removed successfully..
        /// </summary>
        internal static string AssignmentRemovedMsg {
            get {
                return ResourceManager.GetString("AssignmentRemovedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment restored successfully..
        /// </summary>
        internal static string AssignmentRestoredMsg {
            get {
                return ResourceManager.GetString("AssignmentRestoredMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignments.
        /// </summary>
        internal static string Assignments {
            get {
                return ResourceManager.GetString("Assignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignments linked.
        /// </summary>
        internal static string AssignmentsLinked {
            get {
                return ResourceManager.GetString("AssignmentsLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment.
        /// </summary>
        internal static string AssignmentsPage {
            get {
                return ResourceManager.GetString("AssignmentsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment data report.
        /// </summary>
        internal static string AssignmentsReport {
            get {
                return ResourceManager.GetString("AssignmentsReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefineAssignment.
        /// </summary>
        internal static string AssignmentStep1Page {
            get {
                return ResourceManager.GetString("AssignmentStep1Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefineGradingCriteria.
        /// </summary>
        internal static string AssignmentStep2Page {
            get {
                return ResourceManager.GetString("AssignmentStep2Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateAssignment.
        /// </summary>
        internal static string AssignmentStep3Page {
            get {
                return ResourceManager.GetString("AssignmentStep3Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveShareAssignment.
        /// </summary>
        internal static string AssignmentStep4Page {
            get {
                return ResourceManager.GetString("AssignmentStep4Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your assignment cannot be sent because there is missing mandatory information. Please make sure you have completed the mandatory fields and have all the assessment criteria covered by tasks..
        /// </summary>
        internal static string AssignmentStep4WarningMessage {
            get {
                return ResourceManager.GetString("AssignmentStep4WarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorised.
        /// </summary>
        internal static string Authorised {
            get {
                return ResourceManager.GetString("Authorised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting approval.
        /// </summary>
        internal static string AwaitingApproval {
            get {
                return ResourceManager.GetString("AwaitingApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string Broadcast {
            get {
                return ResourceManager.GetString("Broadcast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewsItem.
        /// </summary>
        internal static string BroadcastPage {
            get {
                return ResourceManager.GetString("BroadcastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy now.
        /// </summary>
        internal static string BuyNow {
            get {
                return ResourceManager.GetString("BuyNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Pearson Resources.
        /// </summary>
        internal static string BuyPearsonResources {
            get {
                return ResourceManager.GetString("BuyPearsonResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to centre assignments.
        /// </summary>
        internal static string CentreAssignments {
            get {
                return ResourceManager.GetString("CentreAssignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to centre courses.
        /// </summary>
        internal static string CentreCourses {
            get {
                return ResourceManager.GetString("CentreCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CourseSearch.
        /// </summary>
        internal static string CentreCoursesPage {
            get {
                return ResourceManager.GetString("CentreCoursesPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centre ID.
        /// </summary>
        internal static string CentreID {
            get {
                return ResourceManager.GetString("CentreID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centre name.
        /// </summary>
        internal static string CentreName {
            get {
                return ResourceManager.GetString("CentreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centre number.
        /// </summary>
        internal static string CentreNumber {
            get {
                return ResourceManager.GetString("CentreNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centre Resources.
        /// </summary>
        internal static string CentreResources {
            get {
                return ResourceManager.GetString("CentreResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change IV.
        /// </summary>
        internal static string ChangeIV {
            get {
                return ResourceManager.GetString("ChangeIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12345678901234567890123456789012345678901234567890.
        /// </summary>
        internal static string Char50 {
            get {
                return ResourceManager.GetString("Char50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClaimRolesView.
        /// </summary>
        internal static string ClaimRolesPage {
            get {
                return ResourceManager.GetString("ClaimRolesPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClaimRoles.
        /// </summary>
        internal static string ClaimRolesPageRedirect {
            get {
                return ResourceManager.GetString("ClaimRolesPageRedirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone.
        /// </summary>
        internal static string Clone {
            get {
                return ResourceManager.GetString("Clone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CloneAssignment.
        /// </summary>
        internal static string CloneAssignmentPage {
            get {
                return ResourceManager.GetString("CloneAssignmentPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone course.
        /// </summary>
        internal static string CloneCourse {
            get {
                return ResourceManager.GetString("CloneCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Course.
        /// </summary>
        internal static string ConfirmCourse {
            get {
                return ResourceManager.GetString("ConfirmCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed.
        /// </summary>
        internal static string Confirmed {
            get {
                return ResourceManager.GetString("Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exiting now will lose any work you&apos;ve done so far creating this course. Click Yes to exit or No to remain on this page..
        /// </summary>
        internal static string ConfirmExitCourseStep1 {
            get {
                return ResourceManager.GetString("ConfirmExitCourseStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit? Your course changes will be saved as draft..
        /// </summary>
        internal static string ConfirmExitCourseStep1New {
            get {
                return ResourceManager.GetString("ConfirmExitCourseStep1New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://uk.pearson.com/content/ped/pei/uk/pearson-uk/en/pearson-privacy/your-data-at-pearson/cookies/cookie-policy.html.
        /// </summary>
        internal static string CookieLearnMoreUrl {
            get {
                return ResourceManager.GetString("CookieLearnMoreUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookie Policy.
        /// </summary>
        internal static string CookiePolicy {
            get {
                return ResourceManager.GetString("CookiePolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Pearson website stores cookies on your computer which help us make the website work better for you..
        /// </summary>
        internal static string CookieText {
            get {
                return ResourceManager.GetString("CookieText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy and Cookies.
        /// </summary>
        internal static string CookieTitle {
            get {
                return ResourceManager.GetString("CookieTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course End Date.
        /// </summary>
        internal static string CourseEndDate {
            get {
                return ResourceManager.GetString("CourseEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Leader.
        /// </summary>
        internal static string CourseLeader {
            get {
                return ResourceManager.GetString("CourseLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses.
        /// </summary>
        internal static string Courses {
            get {
                return ResourceManager.GetString("Courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses linked.
        /// </summary>
        internal static string CoursesLinked {
            get {
                return ResourceManager.GetString("CoursesLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course.
        /// </summary>
        internal static string CoursesPage {
            get {
                return ResourceManager.GetString("CoursesPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course data report.
        /// </summary>
        internal static string CoursesReport {
            get {
                return ResourceManager.GetString("CoursesReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Start Date.
        /// </summary>
        internal static string CourseStartDate {
            get {
                return ResourceManager.GetString("CourseStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectQualification.
        /// </summary>
        internal static string CourseStep1Page {
            get {
                return ResourceManager.GetString("CourseStep1Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectCourseUnits.
        /// </summary>
        internal static string CourseStep2Page {
            get {
                return ResourceManager.GetString("CourseStep2Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FinaliseCourse.
        /// </summary>
        internal static string CourseStep3Page {
            get {
                return ResourceManager.GetString("CourseStep3Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course team added.
        /// </summary>
        internal static string CourseTeamAdded {
            get {
                return ResourceManager.GetString("CourseTeamAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string CourseViewPage {
            get {
                return ResourceManager.GetString("CourseViewPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create a course.
        /// </summary>
        internal static string CreateACourse {
            get {
                return ResourceManager.GetString("CreateACourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create an assignment.
        /// </summary>
        internal static string CreateAnAssignment {
            get {
                return ResourceManager.GetString("CreateAnAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create coversheet.
        /// </summary>
        internal static string CreateCoversheet {
            get {
                return ResourceManager.GetString("CreateCoversheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation date.
        /// </summary>
        internal static string CreationDate {
            get {
                return ResourceManager.GetString("CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Status.
        /// </summary>
        internal static string CurrentStatus {
            get {
                return ResourceManager.GetString("CurrentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date approved.
        /// </summary>
        internal static string DateApproved {
            get {
                return ResourceManager.GetString("DateApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date role claimed.
        /// </summary>
        internal static string DateRoleClaimed {
            get {
                return ResourceManager.GetString("DateRoleClaimed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date/time opted out.
        /// </summary>
        internal static string DatetimeOptedOut {
            get {
                return ResourceManager.GetString("DatetimeOptedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDM review.
        /// </summary>
        internal static string DDMReview {
            get {
                return ResourceManager.GetString("DDMReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declined.
        /// </summary>
        internal static string Declined {
            get {
                return ResourceManager.GetString("Declined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        internal static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTE: Please do not reply to this email as it cannot be delivered. If you wish to contact us then please use the existing Edexcel contact processes available at http://www.edexcel.com/contactus..
        /// </summary>
        internal static string DoNotReplyMessage {
            get {
                return ResourceManager.GetString("DoNotReplyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download course.
        /// </summary>
        internal static string DownloadCourse {
            get {
                return ResourceManager.GetString("DownloadCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download PDF.
        /// </summary>
        internal static string DownloadPDF {
            get {
                return ResourceManager.GetString("DownloadPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft.
        /// </summary>
        internal static string Draft {
            get {
                return ResourceManager.GetString("Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditAssignment.
        /// </summary>
        internal static string EditAssignmentStep1Page {
            get {
                return ResourceManager.GetString("EditAssignmentStep1Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit course.
        /// </summary>
        internal static string EditCourse {
            get {
                return ResourceManager.GetString("EditCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing.
        /// </summary>
        internal static string Editing {
            get {
                return ResourceManager.GetString("Editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \r\n        Dear {0} {1} \r\n\r\n\r\nYou have been added to the following course within myBTEC:\r\n\r\n\r\n\r\n{2}\r\n\r\n\r\n\r\nYour role on the course is {3}.\r\n\r\n\r\nIf you have any questions please contact {4} {5}  who added you to this course. The email address to use is {6}.\r\n\r\n\r\nThank you.\r\n\r\n\r\n{7}\r\n    \r\n\r\n.
        /// </summary>
        internal static string EmailBodyAddedInCourseTeam {
            get {
                return ResourceManager.GetString("EmailBodyAddedInCourseTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \r\n        Dear {0} {1}\r\n        \r\n        The following assignment has been reviewed by the Internal Verifier.\r\n        \r\n        Assignment Brief title: {2}\r\n        Creator: {0} {1}\r\n        Subject: {3}\r\n        Courses: {4}\r\n         \r\n        Please  log in to myBTEC, find this assignment brief and then choose View IV feedback in the Action dropdown. \r\n        \r\n        Thank you.\r\n        \r\n        {5}\r\n    \r\n\r\n.
        /// </summary>
        internal static string EmailBodyAssignmentApproved {
            get {
                return ResourceManager.GetString("EmailBodyAssignmentApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0} {1}\r\n        \r\n        Unfortunately your assignment [{2}] has been rejected by {3} {4}.\r\n        \r\n         \r\n        Please  log in to myBTEC and check the assignment review form for details.\r\n        \r\n        {5}\r\n    \r\n\r\n.
        /// </summary>
        internal static string EmailBodyAssignmentRejected {
            get {
                return ResourceManager.GetString("EmailBodyAssignmentRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \r\n        Dear {0} {1}\r\n        \r\n        The following assignment has been sent to you for review.\r\n        \r\n        Assignment Brief title: {2}\r\n        Creator: {3} {4}\r\n        Subject: {5}\r\n        Courses: {6}\r\n         \r\n        Please  log in to myBTEC, find this assignment brief and then choose Review in the Action dropdown. \r\n        \r\n        Thank you.\r\n        \r\n        {7}\r\n.
        /// </summary>
        internal static string EmailBodyAssignmentSentToIv {
            get {
                return ResourceManager.GetString("EmailBodyAssignmentSentToIv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \r\n\r\nException Code\r\n\r\n{0}\r\n\r\n\r\n\r\nUser\r\n\r\n{1}\r\n\r\n\r\n\r\nCentre\r\n\r\n{2}\r\n\r\n\r\n\r\nException Message\r\n\r\n{3}\r\n\r\n\r\n\r\nStack Trace\r\n\r\n{4}\r\n\r\n\r\n\r\n.
        /// </summary>
        internal static string EmailBodyErrorFeedback {
            get {
                return ResourceManager.GetString("EmailBodyErrorFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \r\n\r\nException Code\r\n\r\n{0}\r\n\r\n\r\n\r\nUser\r\n\r\n{1}\r\n\r\n\r\n\r\nCentre\r\n\r\n{2}\r\n\r\n\r\n\r\nDescription\r\n\r\n{3}\n\n\r\n\r\n\r\n\r\n\r\nException Message\r\n\r\n{4}\r\n\r\n\r\n\r\nStack Trace\r\n\r\n{5}\r\n\r\n\r\n\r\n.
        /// </summary>
        internal static string EmailBodyErrorFeedbackWithDscr {
            get {
                return ResourceManager.GetString("EmailBodyErrorFeedbackWithDscr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \r\n      Dear {0} {1} \r\n      \r\n      Your role of {2} on the {3} course has been removed.\r\n            \r\n      If you have any questions please contact {4} {5}  who removed your role. The email address to use is {6}. \r\n            \r\n      Thank you. \r\n      \r\n      {7}\r\n    \r\n\r\n.
        /// </summary>
        internal static string EmailBodyRemovedFromCourseTeam {
            get {
                return ResourceManager.GetString("EmailBodyRemovedFromCourseTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \r\n      The user {0} {1} has approved your role claim as {2} for {3}\r\n      \r\n      You may now log into myBTEC and carry out actions appropriate to that role.\r\n      \r\n      {4}\r\n    \r\n\r\n.
        /// </summary>
        internal static string EmailBodyRoleApproved {
            get {
                return ResourceManager.GetString("EmailBodyRoleApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \r\n\r\n \r\nThe user {0} {1} ({2}) has claimed the following role(s) within myBTEC;\r\n\r\n\n\n\r\n\r\n\r\n\r\n{3}\r\n\r\n\n\n\r\n\r\n\r\n\r\nPlease visit the ‘User role approval’ page to approve or decline these claims.\r\n\r\n\r\n{4}\r\n\r\n\r\n.
        /// </summary>
        internal static string EmailBodyRoleClaimed {
            get {
                return ResourceManager.GetString("EmailBodyRoleClaimed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \r\n      The user {0} {1} has declined your role claim as {2} for {3}\r\n      \r\n      If you feel this is incorrect you should contact them directly. Otherwise please log into myBTEC and claim a different role.\r\n      \r\n      {4}\r\n    \r\n\r\n.
        /// </summary>
        internal static string EmailBodyRoleDeclined {
            get {
                return ResourceManager.GetString("EmailBodyRoleDeclined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject: {0} \r\nRole claimed: {1} .
        /// </summary>
        internal static string EmailRoleClaimed {
            get {
                return ResourceManager.GetString("EmailRoleClaimed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \r\n\r\n\n\n\r\n.
        /// </summary>
        internal static string EmailRoleClaimedNewRow {
            get {
                return ResourceManager.GetString("EmailRoleClaimedNewRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to myBTEC - Assignment Brief Review.
        /// </summary>
        internal static string EmailSubjectAssignmentApproved {
            get {
                return ResourceManager.GetString("EmailSubjectAssignmentApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to myBTEC - Your assignment [{0}] has been rejected.
        /// </summary>
        internal static string EmailSubjectAssignmentRejected {
            get {
                return ResourceManager.GetString("EmailSubjectAssignmentRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to myBTEC - Assignment Brief Review.
        /// </summary>
        internal static string EmailSubjectAssignmentSentToIv {
            get {
                return ResourceManager.GetString("EmailSubjectAssignmentSentToIv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to myBTEC - Course Leaders.
        /// </summary>
        internal static string EmailSubjectCourseLeaderAdded {
            get {
                return ResourceManager.GetString("EmailSubjectCourseLeaderAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to myBTEC feedback - Feedback on Exception.
        /// </summary>
        internal static string EmailSubjectErrorFeedback {
            get {
                return ResourceManager.GetString("EmailSubjectErrorFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to myBTEC - Role removed from course team.
        /// </summary>
        internal static string EmailSubjectRemovedFromCourseTeam {
            get {
                return ResourceManager.GetString("EmailSubjectRemovedFromCourseTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to myBTEC - You have been approved as {0} for {1}.
        /// </summary>
        internal static string EmailSubjectRoleApproved {
            get {
                return ResourceManager.GetString("EmailSubjectRoleApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to myBTEC - New myBTEC roles need approving.
        /// </summary>
        internal static string EmailSubjectRoleClaimed {
            get {
                return ResourceManager.GetString("EmailSubjectRoleClaimed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to myBTEC - Your claim as {0} for {1} has been declined.
        /// </summary>
        internal static string EmailSubjectRoleDeclined {
            get {
                return ResourceManager.GetString("EmailSubjectRoleDeclined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to myBTEC - Team members.
        /// </summary>
        internal static string EmailSubjectTeamMemberAdded {
            get {
                return ResourceManager.GetString("EmailSubjectTeamMemberAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot create coversheet for course assignment because you are not a team member for this course..
        /// </summary>
        internal static string ErrorCanNotCreateCoversheet {
            get {
                return ResourceManager.GetString("ErrorCanNotCreateCoversheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot remove assignment from course because you are not a team member for this course..
        /// </summary>
        internal static string ErrorCanNotRemoveAssignment {
            get {
                return ResourceManager.GetString("ErrorCanNotRemoveAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorFeedback.
        /// </summary>
        internal static string ErrorFeedbackPage {
            get {
                return ResourceManager.GetString("ErrorFeedbackPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add any details of what you were trying to do and click &apos;send&apos; so we can investigate further..
        /// </summary>
        internal static string ErrorFeedbackText {
            get {
                return ResourceManager.GetString("ErrorFeedbackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you.
        /// </summary>
        internal static string ErrorFeedbackThankYou {
            get {
                return ResourceManager.GetString("ErrorFeedbackThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something has gone wrong.....
        /// </summary>
        internal static string ErrorFeedbackTitle {
            get {
                return ResourceManager.GetString("ErrorFeedbackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End User License Agreement.
        /// </summary>
        internal static string EULA {
            get {
                return ResourceManager.GetString("EULA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I Agree.
        /// </summary>
        internal static string EULAIAgree {
            get {
                return ResourceManager.GetString("EULAIAgree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export as excel.
        /// </summary>
        internal static string ExportAsExcel {
            get {
                return ResourceManager.GetString("ExportAsExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External links.
        /// </summary>
        internal static string ExternalLinks {
            get {
                return ResourceManager.GetString("ExternalLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        internal static string ExternalLinksPage {
            get {
                return ResourceManager.GetString("ExternalLinksPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External test.
        /// </summary>
        internal static string ExternalTest {
            get {
                return ResourceManager.GetString("ExternalTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        internal static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        internal static string FeedbackPage {
            get {
                return ResourceManager.GetString("FeedbackPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The myBTEC team want to keep improving our website and our services to you. We need you to tell us what you think! Please contact us at http://www.edexcel.com/contactus.
        /// </summary>
        internal static string FeedbackText {
            get {
                return ResourceManager.GetString("FeedbackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.edexcel.com/Aboutus/contact-us/Pages/home.aspx.
        /// </summary>
        internal static string FeedbackUrl {
            get {
                return ResourceManager.GetString("FeedbackUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final submission.
        /// </summary>
        internal static string FinalSubmission {
            get {
                return ResourceManager.GetString("FinalSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First submission.
        /// </summary>
        internal static string FirstSubmission {
            get {
                return ResourceManager.GetString("FirstSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://uk.pearson.com/pearson-privacy/your-data-at-pearson/cookies/cookie-policy.
        /// </summary>
        internal static string FooterCookiePolicyUrl {
            get {
                return ResourceManager.GetString("FooterCookiePolicyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://qualifications.pearson.com/en/support/Services/myBTEC.html.
        /// </summary>
        internal static string FooterLearnMoreUrl {
            get {
                return ResourceManager.GetString("FooterLearnMoreUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://uk.pearson.com/pearson-privacy/policy/privacy-policy.
        /// </summary>
        internal static string FooterPrivacyPolicyUrl {
            get {
                return ResourceManager.GetString("FooterPrivacyPolicyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helpful pages\r\nhome\r\nclaim roles\r\nuser role approval\r\nhelp\r\nfeedback\r\nlearn more\r\nCourses\r\nmy courses\r\ncentre courses\r\ncreate a course\r\nview qualification\r\nAssignments\r\nmy assignments\r\ncentre assignments\r\ncreate an assignment\r\nLegal\r\ncookie policy\r\nprivacy policy\r\nterms of use\r\nlog out.
        /// </summary>
        internal static string FooterText {
            get {
                return ResourceManager.GetString("FooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Assignment Checking Service.
        /// </summary>
        internal static string GoToACS {
            get {
                return ResourceManager.GetString("GoToACS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View {0} - {1} of {2}.
        /// </summary>
        internal static string GridDataCounter {
            get {
                return ResourceManager.GetString("GridDataCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string HelpPage {
            get {
                return ResourceManager.GetString("HelpPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Verifier.
        /// </summary>
        internal static string InternalVerifier {
            get {
                return ResourceManager.GetString("InternalVerifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IV.
        /// </summary>
        internal static string IV {
            get {
                return ResourceManager.GetString("IV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead Internal Verifier.
        /// </summary>
        internal static string LeadInternalVerifier {
            get {
                return ResourceManager.GetString("LeadInternalVerifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn More.
        /// </summary>
        internal static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linked to course.
        /// </summary>
        internal static string LinkedToCourse {
            get {
                return ResourceManager.GetString("LinkedToCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        internal static string Links {
            get {
                return ResourceManager.GetString("Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to courses.
        /// </summary>
        internal static string LinkToCourses {
            get {
                return ResourceManager.GetString("LinkToCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIV.
        /// </summary>
        internal static string LIV {
            get {
                return ResourceManager.GetString("LIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live.
        /// </summary>
        internal static string Live {
            get {
                return ResourceManager.GetString("Live", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live edit.
        /// </summary>
        internal static string LiveEdit {
            get {
                return ResourceManager.GetString("LiveEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login date and time .
        /// </summary>
        internal static string LoginDateTime {
            get {
                return ResourceManager.GetString("LoginDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginPage {
            get {
                return ResourceManager.GetString("LoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login activity report.
        /// </summary>
        internal static string LoginReport {
            get {
                return ResourceManager.GetString("LoginReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log out.
        /// </summary>
        internal static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article saved.
        /// </summary>
        internal static string MsgArticleSaved {
            get {
                return ResourceManager.GetString("MsgArticleSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link with title {0} successfully {1}. Please refresh the page to {2} link in Links menu tab..
        /// </summary>
        internal static string MsgExternalLinkSaved {
            get {
                return ResourceManager.GetString("MsgExternalLinkSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my assignments.
        /// </summary>
        internal static string MyAssignments {
            get {
                return ResourceManager.GetString("MyAssignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my courses.
        /// </summary>
        internal static string MyCourses {
            get {
                return ResourceManager.GetString("MyCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not approved.
        /// </summary>
        internal static string NotApproved {
            get {
                return ResourceManager.GetString("NotApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need Improvement.
        /// </summary>
        internal static string NotApprovedFeedback {
            get {
                return ResourceManager.GetString("NotApprovedFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: When cloning an assignment you cannot change the subject or qualification suite..
        /// </summary>
        internal static string NoteCloneAssignment {
            get {
                return ResourceManager.GetString("NoteCloneAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note: You cannot currently send this assignment for review as your role is still in a pending state for this subject. You must have your role approved in this subject before you can send this assignment for review..
        /// </summary>
        internal static string NotePendingUserAssignmentStep4 {
            get {
                return ResourceManager.GetString("NotePendingUserAssignmentStep4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your course is ready to be confirmed but please note: You cannot currently confirm this course as your role is still in a pending state for this subject. You must have your role approved in this subject before you can confirm this course..
        /// </summary>
        internal static string NotePendingUserCourseStep3 {
            get {
                return ResourceManager.GetString("NotePendingUserCourseStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note: Items on this wish list will only be displayed for 90 days..
        /// </summary>
        internal static string NoteWishList90Days {
            get {
                return ResourceManager.GetString("NoteWishList90Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opt out data report.
        /// </summary>
        internal static string OptOutReport {
            get {
                return ResourceManager.GetString("OptOutReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Based on your usage of myBTEC, we will send you emails and communications recommending how you can make even better use of myBTEC services. Tick here if you do not want to receive this information..
        /// </summary>
        internal static string OptOutText {
            get {
                return ResourceManager.GetString("OptOutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pathway.
        /// </summary>
        internal static string Pathway {
            get {
                return ResourceManager.GetString("Pathway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pearson.
        /// </summary>
        internal static string Pearson {
            get {
                return ResourceManager.GetString("Pearson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pearson.
        /// </summary>
        internal static string PearsonCentre {
            get {
                return ResourceManager.GetString("PearsonCentre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pearson Resources.
        /// </summary>
        internal static string PearsonResources {
            get {
                return ResourceManager.GetString("PearsonResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        internal static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QAN.
        /// </summary>
        internal static string QAN {
            get {
                return ResourceManager.GetString("QAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualification.
        /// </summary>
        internal static string Qualification {
            get {
                return ResourceManager.GetString("Qualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edexcel BTEC Level 1/Level 2 First Award in Sport (Award).
        /// </summary>
        internal static string QualificationAwardSport {
            get {
                return ResourceManager.GetString("QualificationAwardSport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edexcel BTEC Level 1/Level 2 First Extended Certificate in Applied Science.
        /// </summary>
        internal static string QualificationCertificateAppliedScience {
            get {
                return ResourceManager.GetString("QualificationCertificateAppliedScience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualification name.
        /// </summary>
        internal static string QualificationName {
            get {
                return ResourceManager.GetString("QualificationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualification suite.
        /// </summary>
        internal static string QualificationSuite {
            get {
                return ResourceManager.GetString("QualificationSuite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read later and go to my BTEC.
        /// </summary>
        internal static string ReadLaterNews {
            get {
                return ResourceManager.GetString("ReadLaterNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from course.
        /// </summary>
        internal static string RemoveFromCourse {
            get {
                return ResourceManager.GetString("RemoveFromCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from Wish List.
        /// </summary>
        internal static string RemoveFromWishList {
            get {
                return ResourceManager.GetString("RemoveFromWishList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string ReportsPage {
            get {
                return ResourceManager.GetString("ReportsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Download.
        /// </summary>
        internal static string ResourceDownloadReport {
            get {
                return ResourceManager.GetString("ResourceDownloadReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        internal static string Resources {
            get {
                return ResourceManager.GetString("Resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource.
        /// </summary>
        internal static string ResourcesPage {
            get {
                return ResourceManager.GetString("ResourcesPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        internal static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        internal static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        internal static string ReviewPage {
            get {
                return ResourceManager.GetString("ReviewPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role claimed.
        /// </summary>
        internal static string RoleClaimed {
            get {
                return ResourceManager.GetString("RoleClaimed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role for centre.
        /// </summary>
        internal static string RoleForCentre {
            get {
                return ResourceManager.GetString("RoleForCentre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role claim report.
        /// </summary>
        internal static string RolesReport {
            get {
                return ResourceManager.GetString("RolesReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select ....
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an action.
        /// </summary>
        internal static string SelectAction {
            get {
                return ResourceManager.GetString("SelectAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a pathway.
        /// </summary>
        internal static string SelectPathway {
            get {
                return ResourceManager.GetString("SelectPathway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select qualification suite.
        /// </summary>
        internal static string SelectQualification {
            get {
                return ResourceManager.GetString("SelectQualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select qualification size.
        /// </summary>
        internal static string SelectSize {
            get {
                return ResourceManager.GetString("SelectSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a subject.
        /// </summary>
        internal static string SelectSubject {
            get {
                return ResourceManager.GetString("SelectSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a unit.
        /// </summary>
        internal static string SelectUnit {
            get {
                return ResourceManager.GetString("SelectUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to ACS.
        /// </summary>
        internal static string SendToACS {
            get {
                return ResourceManager.GetString("SendToACS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to IV.
        /// </summary>
        internal static string SendToIV {
            get {
                return ResourceManager.GetString("SendToIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SendToIv.
        /// </summary>
        internal static string SendToIvPage {
            get {
                return ResourceManager.GetString("SendToIvPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your myBTEC session is about to time-out. Would you like to remain logged on?.
        /// </summary>
        internal static string SessionExpires {
            get {
                return ResourceManager.GetString("SessionExpires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time remaining:.
        /// </summary>
        internal static string SessionTimeRemaining {
            get {
                return ResourceManager.GetString("SessionTimeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site QN.
        /// </summary>
        internal static string SiteQN {
            get {
                return ResourceManager.GetString("SiteQN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        internal static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit enquiry.
        /// </summary>
        internal static string SubmitEnquiry {
            get {
                return ResourceManager.GetString("SubmitEnquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher.
        /// </summary>
        internal static string Teacher {
            get {
                return ResourceManager.GetString("Teacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Use.
        /// </summary>
        internal static string TermsOfUse {
            get {
                return ResourceManager.GetString("TermsOfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms.
        /// </summary>
        internal static string TermsPage {
            get {
                return ResourceManager.GetString("TermsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JONATHAN SOANES.
        /// </summary>
        internal static string TestCentreName {
            get {
                return ResourceManager.GetString("TestCentreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99000 99000 99000.
        /// </summary>
        internal static string TestCentreNumber {
            get {
                return ResourceManager.GetString("TestCentreNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;https://www.google.md/search?q={0}&quot;&gt;{0}&lt;/a&gt;.
        /// </summary>
        internal static string TestLink {
            get {
                return ResourceManager.GetString("TestLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test{0}.
        /// </summary>
        internal static string TestText {
            get {
                return ResourceManager.GetString("TestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.google.com/search?q={0}.
        /// </summary>
        internal static string TestUrl {
            get {
                return ResourceManager.GetString("TestUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you do not have permission to access myBTEC. If you are a centre user please contact your Exams Officer or Centre Administrator..
        /// </summary>
        internal static string UnauthorisedText {
            get {
                return ResourceManager.GetString("UnauthorisedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access not allowed.
        /// </summary>
        internal static string UnauthorisedTitle {
            get {
                return ResourceManager.GetString("UnauthorisedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        internal static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User email address.
        /// </summary>
        internal static string UserEmailAddress {
            get {
                return ResourceManager.GetString("UserEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        internal static string UserID {
            get {
                return ResourceManager.GetString("UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoleApproval.
        /// </summary>
        internal static string UserRoleApprovalPage {
            get {
                return ResourceManager.GetString("UserRoleApprovalPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add at least one Assessor to coversheet..
        /// </summary>
        internal static string ValidationAddAssessor {
            get {
                return ResourceManager.GetString("ValidationAddAssessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add at least one Internal Verifier to coversheet..
        /// </summary>
        internal static string ValidationAddIV {
            get {
                return ResourceManager.GetString("ValidationAddIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessment and grading criteria for unit: {0}.
        /// </summary>
        internal static string ValidationAssessmentAndGradingCriteriaForUnit {
            get {
                return ResourceManager.GetString("ValidationAssessmentAndGradingCriteriaForUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one assessment criteria should be selected for each unit..
        /// </summary>
        internal static string ValidationAssessmentCriteriaMissing {
            get {
                return ResourceManager.GetString("ValidationAssessmentCriteriaMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please indicate whether this assignment brief covers a whole unit or part(s) of unit(s)..
        /// </summary>
        internal static string ValidationAssignmentCoverage {
            get {
                return ResourceManager.GetString("ValidationAssignmentCoverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation did not succeed..
        /// </summary>
        internal static string ValidationDidNotSucceed {
            get {
                return ResourceManager.GetString("ValidationDidNotSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN should be a 13 digit number without any spaces. It should also not contain only zeros - free resources are accessible in Centre resources tab..
        /// </summary>
        internal static string ValidationErrorISBN {
            get {
                return ResourceManager.GetString("ValidationErrorISBN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is required..
        /// </summary>
        internal static string ValidationFieldRequired {
            get {
                return ResourceManager.GetString("ValidationFieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coversheet Final Submission date cannot be later than Course End date..
        /// </summary>
        internal static string ValidationFinalSubmissionLaterEndDate {
            get {
                return ResourceManager.GetString("ValidationFinalSubmissionLaterEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coversheet First Submission date cannot be later than Final Submission date..
        /// </summary>
        internal static string ValidationFirstSubmissionLaterFinal {
            get {
                return ResourceManager.GetString("ValidationFirstSubmissionLaterFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML tags and scripts are not allowed!.
        /// </summary>
        internal static string ValidationHtmlTags {
            get {
                return ResourceManager.GetString("ValidationHtmlTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be a string with a maximum length of {1}..
        /// </summary>
        internal static string ValidationLength {
            get {
                return ResourceManager.GetString("ValidationLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This course has no {0} added. Please add an {0} to the course team before creating any coversheets..
        /// </summary>
        internal static string ValidationNoTeamForCoversheet {
            get {
                return ResourceManager.GetString("ValidationNoTeamForCoversheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one unit..
        /// </summary>
        internal static string ValidationNoUnitsAdded {
            get {
                return ResourceManager.GetString("ValidationNoUnitsAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field can only contain alpha numeric characters. Special characters are not supported.
        /// </summary>
        internal static string ValidationSpecialChars {
            get {
                return ResourceManager.GetString("ValidationSpecialChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coversheet Start date cannot be earlier than Course Start date..
        /// </summary>
        internal static string ValidationStartDateEarlierCourseStartDate {
            get {
                return ResourceManager.GetString("ValidationStartDateEarlierCourseStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coversheet Start date cannot be later than First Submission date..
        /// </summary>
        internal static string ValidationStartDateLaterFirst {
            get {
                return ResourceManager.GetString("ValidationStartDateLaterFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View IV feedback.
        /// </summary>
        internal static string ViewIvFeedback {
            get {
                return ResourceManager.GetString("ViewIvFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View qualification.
        /// </summary>
        internal static string ViewQualification {
            get {
                return ResourceManager.GetString("ViewQualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewQualification.
        /// </summary>
        internal static string ViewQualificationStep1 {
            get {
                return ResourceManager.GetString("ViewQualificationStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewQualificationUnits.
        /// </summary>
        internal static string ViewQualificationStep2 {
            get {
                return ResourceManager.GetString("ViewQualificationStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wish List.
        /// </summary>
        internal static string WishList {
            get {
                return ResourceManager.GetString("WishList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Resource pack:{1:C}.
        /// </summary>
        internal static string WishListSummaryOnePack {
            get {
                return ResourceManager.GetString("WishListSummaryOnePack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Resource packs:{1:C}.
        /// </summary>
        internal static string WishListSummaryPacks {
            get {
                return ResourceManager.GetString("WishListSummaryPacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With IV.
        /// </summary>
        internal static string WithIV {
            get {
                return ResourceManager.GetString("WithIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
